export const SET_STATS = 'SET_STATS'
export const SET_JOBS = 'SET_JOBS'
export const ADD_JOB = 'ADD_JOB'
export const UPDATE_JOB = 'UPDATE_JOB'
export const DELETE_JOB = 'DELETE_JOB'
export const SET_EDIT_JOB_ID = 'SET_EDIT_JOB_ID'
export const SET_IS_EDIT_MODE = 'SET_IS_EDIT_MODE'
export const SET_POP_UP_JOB_ID = 'SET_POP_UP_JOB_ID'
